### ISSUE TITLE
CSS Custom Properties

### ISSUE THREAD

**Issue by marcjulian** [fivethree-team/vscode-ionic-snippets#13]
# Feature Request

Add CSS Custom Properties for all component as snippet.

## Ionic Components

**TODO** add remaining components

- [x] ion-anchor
- [x] ion-action-sheet
- [x] ion-alert
- [x] ion-badge
- [x] ion-button
- [x] ion-card
- [x] ion-card-subtitle
- [x] ion-card-title
- [X] ion-checkbox
- [x] ion-chip
- [x] ion-col
- [x] ion-content
- [x] ion-datetime
- [x] ion-picker
- [x] ion-fab-button
- [x] ion-grid
- [x] ion-item
- [x] ion-item-divider
- [x] ion-item-option
- [x] ion-input
- [x] ion-label
- [x] ion-list-header
- [x] ion-loading
- [x] ion-note
- [x] ion-picker
- [x] ion-progress-bar
- [x] ion-range
- [x] ion-skeleton-text
- [x] ion-slides
- [x] ion-split-pane
- [x] ion-spinner
- [x] ion-tab-bar
- [x] ion-tab-button
- [x] ion-textarea
- [x] ion-thumbnail
- [x] ion-title
- [x] ion-toast
- [x] ion-toggle
- [x] ion-toolbar
